name: baity
description: "A mobile youth house manager to discover places to stay."
publish_to: 'none'
version: 0.3.1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  url_launcher: ^6.3.1
  firebase_core: 2.27.0
  cloud_firestore: 4.15.8
  firebase_auth: 4.17.8
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.2.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib\assets\data\algeria_cities.json
    - lib/assets/images/


l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart